### ISSUE TITLE
Unrecognized UK phone numbers

### ISSUE THREAD

**Issue by Tug** [Automattic/node-phone#17]
I just bought a UK phone number on Twilio today and noticed it wasn't allowed on calypso:

![image](https://user-images.githubusercontent.com/230230/35000811-a051ae40-fae5-11e7-80a6-c6a733c0b1e7.png)

Here is the format: `+441233800000` (last 5 digits have been replaced by 0s).

Should update from upstream maybe?

**Comment by yoavf** [comment]
@Tug that number starts with a prefix dedicated to landlines (specifically, in Ashford (Kent)) according to [the UK's national numbering plan](https://www.ofcom.org.uk/__data/assets/pdf_file/0013/102613/national-numbering-plan.pdf)

We validate for known mobile prefix where possible.

**Comment by Tug** [comment]
@yoavf Oh I see, thanks for investigating! That makes sense 👍
