### ISSUE TITLE
Alpha 3 - Alpha 2 problem

### ISSUE THREAD

**Issue by gokhanozgezer** [Automattic/node-phone#24]
Hi, I need alpha2 but you return only alpha3 or please return both of [alpha3, alpha2]

`module.exports = function (phone, country, alpha) {...}`

`const formatAlpha = (alpha === null || typeof alpha !== 'string' || (alpha.trim() !== 'alpha2' || alpha.trim() !== 'alpha3')) ? 'alpha3' : alpha.trim();`

`if (validate_phone_iso3166(formatPhone, iso3166)) {
		return ['+' + formatPhone, iso3166[formatAlpha]];
	}`

**Comment by taggon** [comment]
Hello @gokhanozgezer,

You can convert Alpha3 country codes to Alpha2 with this package:
https://github.com/vtex/country-iso-3-to-2

**Comment by gokhanozgezer** [comment]
thanx
